import type { ExamAttempt, Mistake } from "./exam-data"

const TEX_SPECIALS = /[#$%&_{}~^\\]/g

function escapeTex(value: string) {
  return value.replace(TEX_SPECIALS, (character) => ({
    "#": "\\#",
    "$": "\\$",
    "%": "\\%",
    "&": "\\&",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "^": "\\textasciicircum{}",
    "\\": "\\textbackslash{}",
  })[character]!)
}

function questionToTex(value: string) {
  return value
    .split(/(\$\$[\s\S]*?\$\$|\\\[[\s\S]*?\\\]|\$[^\n$]+\$|\\\([^\n]*?\\\))/g)
    .map((part) => /^(\$|\\\[|\\\()/.test(part) ? part : escapeTex(part).replace(/\r?\n{2,}/g, "\n\n\\par\n").replace(/\r?\n/g, " "))
    .join("")
}

export function buildMistakesTex(mistakes: Mistake[], attempts: ExamAttempt[]) {
  const attemptMap = new Map(attempts.map((attempt) => [attempt.id, attempt]))
  const pages = mistakes.map((mistake, index) => {
    const attempt = attemptMap.get(mistake.attemptId)
    const context = attempt
      ? `${attempt.subject} - ${attempt.provider} ${attempt.examYear} ${attempt.paper}`
      : "Deleted exam"
    const marks = mistake.totalMarks === undefined ? "" : `\\hfill\\fbox{\\rule{0pt}{1.4em}\\hspace{2em} / ${mistake.totalMarks}}`

    return `\\section*{${index + 1}. ${escapeTex(mistake.question)}}
\\textcolor{gray}{${escapeTex(context)}}${marks}

\\vspace{0.8em}
${questionToTex(mistake.questionText?.trim() || mistake.question)}

\\vspace{1.5em}
\\textbf{Working}
\\worklines{10}`
  })

  return `% ExamTrack mistake worksheet
\\documentclass[11pt,a4paper]{article}
\\usepackage[margin=18mm]{geometry}
\\usepackage{amsmath,amssymb}
\\usepackage{xcolor}
\\pagestyle{plain}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0.5em}
\\newcount\\workline
\\newcommand{\\worklines}[1]{\\workline=0\\loop\\ifnum\\workline<#1\\vspace{1.15em}\\hrulefill\\par\\advance\\workline by 1\\repeat}
\\begin{document}
\\begin{center}
{\\LARGE\\bfseries Mistake Practice Worksheet}\\par
\\small Generated by ExamTrack - ${new Date().toLocaleDateString("en-AU")}
\\end{center}
\\vspace{1em}
${pages.join("\n\\newpage\n")}
\\end{document}
`
}

export async function downloadMistakesPdf(mistakes: Mistake[], attempts: ExamAttempt[], subject = "mistakes") {
  const response = await fetch("/api/mistakes-pdf", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ tex: buildMistakesTex(mistakes, attempts) }),
  })
  if (!response.ok) throw new Error((await response.text()).slice(0, 500) || "PDF compilation failed.")

  const url = URL.createObjectURL(await response.blob())
  const link = document.createElement("a")
  link.href = url
  link.download = `${subject.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "mistakes"}-worksheet.pdf`
  link.click()
  URL.revokeObjectURL(url)
}
